/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 63
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_player_selector = 2,
  anon_sym_LBRACK = 3,
  anon_sym_COMMA = 4,
  anon_sym_RBRACK = 5,
  anon_sym_EQ = 6,
  anon_sym_name = 7,
  anon_sym_r = 8,
  anon_sym_rx = 9,
  sym_negation = 10,
  sym_integer = 11,
  sym_text = 12,
  sym_selector_var_nearest_player = 13,
  sym_selector_var_nearest_entity = 14,
  sym_selector_var_random_player = 15,
  sym_selector_var_all_players = 16,
  sym_selector_var_all_entities = 17,
  sym_selector_var_self = 18,
  sym_selector_var_initiator = 19,
  anon_sym_SLASH = 20,
  anon_sym_nether = 21,
  anon_sym_overworld = 22,
  anon_sym_the_end = 23,
  sym_entity_keyword = 24,
  sym_execute_keyword = 25,
  sym_if_keyword = 26,
  sym_in_keyword = 27,
  sym_replaceitem_keyword = 28,
  sym_run_keyword = 29,
  sym_say_keyword = 30,
  sym_tell_keyword = 31,
  sym_tellraw_keyword = 32,
  sym_unless_keyword = 33,
  aux_sym_rest_token1 = 34,
  sym__ws = 35,
  sym_replacitem_slot = 36,
  sym_item = 37,
  sym_source_file = 38,
  sym_selector = 39,
  sym_selector_variable = 40,
  sym_selector_arguments = 41,
  sym_selector_argument = 42,
  sym_selector_arg_key = 43,
  sym_selector_arg_value = 44,
  sym_command = 45,
  sym_execute_command = 46,
  sym_execute_if_subcommand = 47,
  sym_execute_in_subcommand = 48,
  sym_execute_unless_subcommand = 49,
  sym_replaceitem_command = 50,
  sym_say_command = 51,
  sym_tell_command = 52,
  sym_tellraw_command = 53,
  sym_rest = 54,
  sym_json = 55,
  aux_sym_source_file_repeat1 = 56,
  aux_sym_selector_arguments_repeat1 = 57,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_player_selector] = "player_selector",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ] = "=",
  [anon_sym_name] = "name",
  [anon_sym_r] = "r",
  [anon_sym_rx] = "rx",
  [sym_negation] = "negation",
  [sym_integer] = "integer",
  [sym_text] = "text",
  [sym_selector_var_nearest_player] = "selector_var_nearest_player",
  [sym_selector_var_nearest_entity] = "selector_var_nearest_entity",
  [sym_selector_var_random_player] = "selector_var_random_player",
  [sym_selector_var_all_players] = "selector_var_all_players",
  [sym_selector_var_all_entities] = "selector_var_all_entities",
  [sym_selector_var_self] = "selector_var_self",
  [sym_selector_var_initiator] = "selector_var_initiator",
  [anon_sym_SLASH] = "/",
  [anon_sym_nether] = "nether",
  [anon_sym_overworld] = "overworld",
  [anon_sym_the_end] = "the_end",
  [sym_entity_keyword] = "entity_keyword",
  [sym_execute_keyword] = "execute_keyword",
  [sym_if_keyword] = "if_keyword",
  [sym_in_keyword] = "in_keyword",
  [sym_replaceitem_keyword] = "replaceitem_keyword",
  [sym_run_keyword] = "run_keyword",
  [sym_say_keyword] = "say_keyword",
  [sym_tell_keyword] = "tell_keyword",
  [sym_tellraw_keyword] = "tellraw_keyword",
  [sym_unless_keyword] = "unless_keyword",
  [aux_sym_rest_token1] = "rest_token1",
  [sym__ws] = "_ws",
  [sym_replacitem_slot] = "replacitem_slot",
  [sym_item] = "item",
  [sym_source_file] = "source_file",
  [sym_selector] = "selector",
  [sym_selector_variable] = "selector_variable",
  [sym_selector_arguments] = "selector_arguments",
  [sym_selector_argument] = "selector_argument",
  [sym_selector_arg_key] = "selector_arg_key",
  [sym_selector_arg_value] = "selector_arg_value",
  [sym_command] = "command",
  [sym_execute_command] = "execute_command",
  [sym_execute_if_subcommand] = "execute_if_subcommand",
  [sym_execute_in_subcommand] = "execute_in_subcommand",
  [sym_execute_unless_subcommand] = "execute_unless_subcommand",
  [sym_replaceitem_command] = "replaceitem_command",
  [sym_say_command] = "say_command",
  [sym_tell_command] = "tell_command",
  [sym_tellraw_command] = "tellraw_command",
  [sym_rest] = "rest",
  [sym_json] = "json",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_selector_arguments_repeat1] = "selector_arguments_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_player_selector] = sym_player_selector,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_name] = anon_sym_name,
  [anon_sym_r] = anon_sym_r,
  [anon_sym_rx] = anon_sym_rx,
  [sym_negation] = sym_negation,
  [sym_integer] = sym_integer,
  [sym_text] = sym_text,
  [sym_selector_var_nearest_player] = sym_selector_var_nearest_player,
  [sym_selector_var_nearest_entity] = sym_selector_var_nearest_entity,
  [sym_selector_var_random_player] = sym_selector_var_random_player,
  [sym_selector_var_all_players] = sym_selector_var_all_players,
  [sym_selector_var_all_entities] = sym_selector_var_all_entities,
  [sym_selector_var_self] = sym_selector_var_self,
  [sym_selector_var_initiator] = sym_selector_var_initiator,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_nether] = anon_sym_nether,
  [anon_sym_overworld] = anon_sym_overworld,
  [anon_sym_the_end] = anon_sym_the_end,
  [sym_entity_keyword] = sym_entity_keyword,
  [sym_execute_keyword] = sym_execute_keyword,
  [sym_if_keyword] = sym_if_keyword,
  [sym_in_keyword] = sym_in_keyword,
  [sym_replaceitem_keyword] = sym_replaceitem_keyword,
  [sym_run_keyword] = sym_run_keyword,
  [sym_say_keyword] = sym_say_keyword,
  [sym_tell_keyword] = sym_tell_keyword,
  [sym_tellraw_keyword] = sym_tellraw_keyword,
  [sym_unless_keyword] = sym_unless_keyword,
  [aux_sym_rest_token1] = aux_sym_rest_token1,
  [sym__ws] = sym__ws,
  [sym_replacitem_slot] = sym_replacitem_slot,
  [sym_item] = sym_item,
  [sym_source_file] = sym_source_file,
  [sym_selector] = sym_selector,
  [sym_selector_variable] = sym_selector_variable,
  [sym_selector_arguments] = sym_selector_arguments,
  [sym_selector_argument] = sym_selector_argument,
  [sym_selector_arg_key] = sym_selector_arg_key,
  [sym_selector_arg_value] = sym_selector_arg_value,
  [sym_command] = sym_command,
  [sym_execute_command] = sym_execute_command,
  [sym_execute_if_subcommand] = sym_execute_if_subcommand,
  [sym_execute_in_subcommand] = sym_execute_in_subcommand,
  [sym_execute_unless_subcommand] = sym_execute_unless_subcommand,
  [sym_replaceitem_command] = sym_replaceitem_command,
  [sym_say_command] = sym_say_command,
  [sym_tell_command] = sym_tell_command,
  [sym_tellraw_command] = sym_tellraw_command,
  [sym_rest] = sym_rest,
  [sym_json] = sym_json,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_selector_arguments_repeat1] = aux_sym_selector_arguments_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_player_selector] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_name] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_r] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rx] = {
    .visible = true,
    .named = false,
  },
  [sym_negation] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_selector_var_nearest_player] = {
    .visible = true,
    .named = true,
  },
  [sym_selector_var_nearest_entity] = {
    .visible = true,
    .named = true,
  },
  [sym_selector_var_random_player] = {
    .visible = true,
    .named = true,
  },
  [sym_selector_var_all_players] = {
    .visible = true,
    .named = true,
  },
  [sym_selector_var_all_entities] = {
    .visible = true,
    .named = true,
  },
  [sym_selector_var_self] = {
    .visible = true,
    .named = true,
  },
  [sym_selector_var_initiator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nether] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_overworld] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_the_end] = {
    .visible = true,
    .named = false,
  },
  [sym_entity_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_execute_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_if_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_in_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_replaceitem_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_run_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_say_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_tell_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_tellraw_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_unless_keyword] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_rest_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [sym_replacitem_slot] = {
    .visible = true,
    .named = true,
  },
  [sym_item] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_selector_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_selector_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_selector_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_selector_arg_key] = {
    .visible = true,
    .named = true,
  },
  [sym_selector_arg_value] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_execute_command] = {
    .visible = true,
    .named = true,
  },
  [sym_execute_if_subcommand] = {
    .visible = true,
    .named = true,
  },
  [sym_execute_in_subcommand] = {
    .visible = true,
    .named = true,
  },
  [sym_execute_unless_subcommand] = {
    .visible = true,
    .named = true,
  },
  [sym_replaceitem_command] = {
    .visible = true,
    .named = true,
  },
  [sym_say_command] = {
    .visible = true,
    .named = true,
  },
  [sym_tell_command] = {
    .visible = true,
    .named = true,
  },
  [sym_tellraw_command] = {
    .visible = true,
    .named = true,
  },
  [sym_rest] = {
    .visible = true,
    .named = true,
  },
  [sym_json] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_selector_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 19,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 26,
  [28] = 28,
  [29] = 23,
  [30] = 25,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 32,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 54,
  [56] = 56,
  [57] = 44,
  [58] = 43,
  [59] = 48,
  [60] = 60,
  [61] = 61,
  [62] = 62,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(79);
      ADVANCE_MAP(
        '!', 90,
        '#', 80,
        ',', 83,
        '/', 100,
        '=', 85,
        '@', 7,
        '[', 82,
        ']', 84,
        'e', 45,
        'i', 32,
        'n', 9,
        'o', 70,
        'r', 87,
        's', 11,
        't', 21,
        'u', 49,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(91);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(114);
      if (lookahead != 0) ADVANCE(115);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(90);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(91);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(77);
      END_STATE();
    case 4:
      if (lookahead == '@') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 5:
      if (lookahead == '[') ADVANCE(82);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(116);
      END_STATE();
    case 6:
      if (lookahead == '_') ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(96);
      if (lookahead == 'e') ADVANCE(97);
      if (lookahead == 'i') ADVANCE(46);
      if (lookahead == 'n') ADVANCE(94);
      if (lookahead == 'p') ADVANCE(93);
      if (lookahead == 'r') ADVANCE(95);
      if (lookahead == 's') ADVANCE(98);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(44);
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(74);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(74);
      if (lookahead == 'l') ADVANCE(51);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(71);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(68);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(69);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(31);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(103);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(102);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(54);
      if (lookahead == 'u') ADVANCE(47);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(41);
      if (lookahead == 'h') ADVANCE(24);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(86);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(105);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 32:
      if (lookahead == 'f') ADVANCE(106);
      if (lookahead == 'n') ADVANCE(107);
      END_STATE();
    case 33:
      if (lookahead == 'h') ADVANCE(29);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(14);
      END_STATE();
    case 35:
      if (lookahead == 'i') ADVANCE(63);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(65);
      END_STATE();
    case 37:
      if (lookahead == 'i') ADVANCE(67);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 39:
      if (lookahead == 'l') ADVANCE(111);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 41:
      if (lookahead == 'l') ADVANCE(39);
      END_STATE();
    case 42:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 43:
      if (lookahead == 'm') ADVANCE(108);
      END_STATE();
    case 44:
      if (lookahead == 'm') ADVANCE(25);
      END_STATE();
    case 45:
      if (lookahead == 'n') ADVANCE(64);
      if (lookahead == 'x') ADVANCE(22);
      END_STATE();
    case 46:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(109);
      END_STATE();
    case 48:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(8);
      if (lookahead == 'r') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(50);
      END_STATE();
    case 51:
      if (lookahead == 'o') ADVANCE(62);
      END_STATE();
    case 52:
      if (lookahead == 'o') ADVANCE(58);
      END_STATE();
    case 53:
      if (lookahead == 'o') ADVANCE(57);
      END_STATE();
    case 54:
      if (lookahead == 'p') ADVANCE(38);
      END_STATE();
    case 55:
      if (lookahead == 'r') ADVANCE(72);
      END_STATE();
    case 56:
      if (lookahead == 'r') ADVANCE(101);
      END_STATE();
    case 57:
      if (lookahead == 'r') ADVANCE(99);
      END_STATE();
    case 58:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 59:
      if (lookahead == 's') ADVANCE(113);
      END_STATE();
    case 60:
      if (lookahead == 's') ADVANCE(59);
      END_STATE();
    case 61:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 62:
      if (lookahead == 't') ADVANCE(3);
      END_STATE();
    case 63:
      if (lookahead == 't') ADVANCE(75);
      END_STATE();
    case 64:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 65:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 66:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 67:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 68:
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 69:
      if (lookahead == 'u') ADVANCE(66);
      END_STATE();
    case 70:
      if (lookahead == 'v') ADVANCE(23);
      END_STATE();
    case 71:
      if (lookahead == 'w') ADVANCE(112);
      END_STATE();
    case 72:
      if (lookahead == 'w') ADVANCE(52);
      END_STATE();
    case 73:
      if (lookahead == 'x') ADVANCE(22);
      END_STATE();
    case 74:
      if (lookahead == 'y') ADVANCE(110);
      END_STATE();
    case 75:
      if (lookahead == 'y') ADVANCE(104);
      END_STATE();
    case 76:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(76);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(118);
      END_STATE();
    case 77:
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(117);
      END_STATE();
    case 78:
      if (eof) ADVANCE(79);
      if (lookahead == '#') ADVANCE(80);
      if (lookahead == '/') ADVANCE(100);
      if (lookahead == 'e') ADVANCE(73);
      if (lookahead == 'r') ADVANCE(19);
      if (lookahead == 's') ADVANCE(10);
      if (lookahead == 't') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_player_selector);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_name);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_r);
      if (lookahead == 'e') ADVANCE(54);
      if (lookahead == 'u') ADVANCE(47);
      if (lookahead == 'x') ADVANCE(89);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_r);
      if (lookahead == 'x') ADVANCE(89);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_rx);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_negation);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_text);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_selector_var_nearest_player);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_selector_var_nearest_entity);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_selector_var_random_player);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_selector_var_all_players);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_selector_var_all_entities);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_selector_var_self);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_selector_var_initiator);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_nether);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_overworld);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_the_end);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_entity_keyword);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_execute_keyword);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_if_keyword);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_in_keyword);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_replaceitem_keyword);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_run_keyword);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_say_keyword);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_tell_keyword);
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_tellraw_keyword);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_unless_keyword);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(aux_sym_rest_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(115);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(aux_sym_rest_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(115);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym__ws);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(116);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_replacitem_slot);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(117);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_item);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(118);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 78},
  [2] = {.lex_state = 78},
  [3] = {.lex_state = 78},
  [4] = {.lex_state = 78},
  [5] = {.lex_state = 78},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 78},
  [10] = {.lex_state = 78},
  [11] = {.lex_state = 78},
  [12] = {.lex_state = 78},
  [13] = {.lex_state = 78},
  [14] = {.lex_state = 78},
  [15] = {.lex_state = 78},
  [16] = {.lex_state = 78},
  [17] = {.lex_state = 78},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 50},
  [20] = {.lex_state = 50},
  [21] = {.lex_state = 50},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 78},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 78},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 78},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 5},
  [56] = {.lex_state = 5},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 5},
  [61] = {.lex_state = 76},
  [62] = {.lex_state = 78},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_name] = ACTIONS(1),
    [anon_sym_r] = ACTIONS(1),
    [anon_sym_rx] = ACTIONS(1),
    [sym_negation] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_selector_var_nearest_player] = ACTIONS(1),
    [sym_selector_var_nearest_entity] = ACTIONS(1),
    [sym_selector_var_random_player] = ACTIONS(1),
    [sym_selector_var_all_players] = ACTIONS(1),
    [sym_selector_var_all_entities] = ACTIONS(1),
    [sym_selector_var_self] = ACTIONS(1),
    [sym_selector_var_initiator] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_nether] = ACTIONS(1),
    [anon_sym_overworld] = ACTIONS(1),
    [anon_sym_the_end] = ACTIONS(1),
    [sym_entity_keyword] = ACTIONS(1),
    [sym_execute_keyword] = ACTIONS(1),
    [sym_if_keyword] = ACTIONS(1),
    [sym_in_keyword] = ACTIONS(1),
    [sym_replaceitem_keyword] = ACTIONS(1),
    [sym_run_keyword] = ACTIONS(1),
    [sym_say_keyword] = ACTIONS(1),
    [sym_tell_keyword] = ACTIONS(1),
    [sym_tellraw_keyword] = ACTIONS(1),
    [sym_unless_keyword] = ACTIONS(1),
    [sym_replacitem_slot] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(47),
    [sym_command] = STATE(3),
    [sym_execute_command] = STATE(9),
    [sym_replaceitem_command] = STATE(9),
    [sym_say_command] = STATE(9),
    [sym_tell_command] = STATE(9),
    [sym_tellraw_command] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_execute_keyword] = ACTIONS(7),
    [sym_replaceitem_keyword] = ACTIONS(9),
    [sym_say_keyword] = ACTIONS(11),
    [sym_tell_keyword] = ACTIONS(13),
    [sym_tellraw_keyword] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(22), 1,
      sym_execute_keyword,
    ACTIONS(25), 1,
      sym_replaceitem_keyword,
    ACTIONS(28), 1,
      sym_say_keyword,
    ACTIONS(31), 1,
      sym_tell_keyword,
    ACTIONS(34), 1,
      sym_tellraw_keyword,
    STATE(2), 2,
      sym_command,
      aux_sym_source_file_repeat1,
    STATE(9), 5,
      sym_execute_command,
      sym_replaceitem_command,
      sym_say_command,
      sym_tell_command,
      sym_tellraw_command,
  [33] = 9,
    ACTIONS(7), 1,
      sym_execute_keyword,
    ACTIONS(9), 1,
      sym_replaceitem_keyword,
    ACTIONS(11), 1,
      sym_say_keyword,
    ACTIONS(13), 1,
      sym_tell_keyword,
    ACTIONS(15), 1,
      sym_tellraw_keyword,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(39), 1,
      sym_comment,
    STATE(2), 2,
      sym_command,
      aux_sym_source_file_repeat1,
    STATE(9), 5,
      sym_execute_command,
      sym_replaceitem_command,
      sym_say_command,
      sym_tell_command,
      sym_tellraw_command,
  [66] = 8,
    ACTIONS(7), 1,
      sym_execute_keyword,
    ACTIONS(9), 1,
      sym_replaceitem_keyword,
    ACTIONS(11), 1,
      sym_say_keyword,
    ACTIONS(13), 1,
      sym_tell_keyword,
    ACTIONS(15), 1,
      sym_tellraw_keyword,
    ACTIONS(41), 1,
      anon_sym_SLASH,
    STATE(12), 1,
      sym_command,
    STATE(9), 5,
      sym_execute_command,
      sym_replaceitem_command,
      sym_say_command,
      sym_tell_command,
      sym_tellraw_command,
  [95] = 7,
    ACTIONS(7), 1,
      sym_execute_keyword,
    ACTIONS(9), 1,
      sym_replaceitem_keyword,
    ACTIONS(11), 1,
      sym_say_keyword,
    ACTIONS(13), 1,
      sym_tell_keyword,
    ACTIONS(15), 1,
      sym_tellraw_keyword,
    STATE(16), 1,
      sym_command,
    STATE(9), 5,
      sym_execute_command,
      sym_replaceitem_command,
      sym_say_command,
      sym_tell_command,
      sym_tellraw_command,
  [121] = 4,
    ACTIONS(43), 1,
      sym_player_selector,
    STATE(26), 1,
      sym_selector_variable,
    STATE(60), 1,
      sym_selector,
    ACTIONS(45), 7,
      sym_selector_var_nearest_player,
      sym_selector_var_nearest_entity,
      sym_selector_var_random_player,
      sym_selector_var_all_players,
      sym_selector_var_all_entities,
      sym_selector_var_self,
      sym_selector_var_initiator,
  [140] = 4,
    ACTIONS(43), 1,
      sym_player_selector,
    STATE(26), 1,
      sym_selector_variable,
    STATE(41), 1,
      sym_selector,
    ACTIONS(45), 7,
      sym_selector_var_nearest_player,
      sym_selector_var_nearest_entity,
      sym_selector_var_random_player,
      sym_selector_var_all_players,
      sym_selector_var_all_entities,
      sym_selector_var_self,
      sym_selector_var_initiator,
  [159] = 4,
    ACTIONS(47), 1,
      sym_player_selector,
    STATE(27), 1,
      sym_selector_variable,
    STATE(45), 1,
      sym_selector,
    ACTIONS(49), 7,
      sym_selector_var_nearest_player,
      sym_selector_var_nearest_entity,
      sym_selector_var_random_player,
      sym_selector_var_all_players,
      sym_selector_var_all_entities,
      sym_selector_var_self,
      sym_selector_var_initiator,
  [178] = 2,
    ACTIONS(53), 1,
      sym_tell_keyword,
    ACTIONS(51), 6,
      ts_builtin_sym_end,
      sym_comment,
      sym_execute_keyword,
      sym_replaceitem_keyword,
      sym_say_keyword,
      sym_tellraw_keyword,
  [190] = 2,
    ACTIONS(57), 1,
      sym_tell_keyword,
    ACTIONS(55), 6,
      ts_builtin_sym_end,
      sym_comment,
      sym_execute_keyword,
      sym_replaceitem_keyword,
      sym_say_keyword,
      sym_tellraw_keyword,
  [202] = 2,
    ACTIONS(61), 1,
      sym_tell_keyword,
    ACTIONS(59), 6,
      ts_builtin_sym_end,
      sym_comment,
      sym_execute_keyword,
      sym_replaceitem_keyword,
      sym_say_keyword,
      sym_tellraw_keyword,
  [214] = 2,
    ACTIONS(65), 1,
      sym_tell_keyword,
    ACTIONS(63), 6,
      ts_builtin_sym_end,
      sym_comment,
      sym_execute_keyword,
      sym_replaceitem_keyword,
      sym_say_keyword,
      sym_tellraw_keyword,
  [226] = 2,
    ACTIONS(69), 1,
      sym_tell_keyword,
    ACTIONS(67), 6,
      ts_builtin_sym_end,
      sym_comment,
      sym_execute_keyword,
      sym_replaceitem_keyword,
      sym_say_keyword,
      sym_tellraw_keyword,
  [238] = 2,
    ACTIONS(73), 1,
      sym_tell_keyword,
    ACTIONS(71), 6,
      ts_builtin_sym_end,
      sym_comment,
      sym_execute_keyword,
      sym_replaceitem_keyword,
      sym_say_keyword,
      sym_tellraw_keyword,
  [250] = 2,
    ACTIONS(77), 1,
      sym_tell_keyword,
    ACTIONS(75), 6,
      ts_builtin_sym_end,
      sym_comment,
      sym_execute_keyword,
      sym_replaceitem_keyword,
      sym_say_keyword,
      sym_tellraw_keyword,
  [262] = 2,
    ACTIONS(81), 1,
      sym_tell_keyword,
    ACTIONS(79), 6,
      ts_builtin_sym_end,
      sym_comment,
      sym_execute_keyword,
      sym_replaceitem_keyword,
      sym_say_keyword,
      sym_tellraw_keyword,
  [274] = 2,
    ACTIONS(85), 1,
      sym_tell_keyword,
    ACTIONS(83), 6,
      ts_builtin_sym_end,
      sym_comment,
      sym_execute_keyword,
      sym_replaceitem_keyword,
      sym_say_keyword,
      sym_tellraw_keyword,
  [286] = 4,
    ACTIONS(87), 1,
      sym_if_keyword,
    ACTIONS(89), 1,
      sym_in_keyword,
    ACTIONS(91), 1,
      sym_unless_keyword,
    STATE(46), 3,
      sym_execute_if_subcommand,
      sym_execute_in_subcommand,
      sym_execute_unless_subcommand,
  [301] = 4,
    ACTIONS(95), 1,
      anon_sym_r,
    STATE(23), 1,
      sym_selector_argument,
    STATE(53), 1,
      sym_selector_arg_key,
    ACTIONS(93), 2,
      anon_sym_name,
      anon_sym_rx,
  [315] = 4,
    ACTIONS(95), 1,
      anon_sym_r,
    STATE(29), 1,
      sym_selector_argument,
    STATE(53), 1,
      sym_selector_arg_key,
    ACTIONS(93), 2,
      anon_sym_name,
      anon_sym_rx,
  [329] = 4,
    ACTIONS(95), 1,
      anon_sym_r,
    STATE(36), 1,
      sym_selector_argument,
    STATE(53), 1,
      sym_selector_arg_key,
    ACTIONS(93), 2,
      anon_sym_name,
      anon_sym_rx,
  [343] = 3,
    ACTIONS(97), 1,
      sym_negation,
    STATE(37), 1,
      sym_selector_arg_value,
    ACTIONS(99), 2,
      sym_integer,
      sym_text,
  [354] = 3,
    ACTIONS(101), 1,
      anon_sym_COMMA,
    ACTIONS(103), 1,
      anon_sym_RBRACK,
    STATE(25), 1,
      aux_sym_selector_arguments_repeat1,
  [364] = 1,
    ACTIONS(105), 3,
      anon_sym_nether,
      anon_sym_overworld,
      anon_sym_the_end,
  [370] = 3,
    ACTIONS(101), 1,
      anon_sym_COMMA,
    ACTIONS(107), 1,
      anon_sym_RBRACK,
    STATE(28), 1,
      aux_sym_selector_arguments_repeat1,
  [380] = 3,
    ACTIONS(109), 1,
      anon_sym_LBRACK,
    ACTIONS(111), 1,
      sym__ws,
    STATE(44), 1,
      sym_selector_arguments,
  [390] = 3,
    ACTIONS(111), 1,
      sym_replacitem_slot,
    ACTIONS(113), 1,
      anon_sym_LBRACK,
    STATE(57), 1,
      sym_selector_arguments,
  [400] = 3,
    ACTIONS(115), 1,
      anon_sym_COMMA,
    ACTIONS(118), 1,
      anon_sym_RBRACK,
    STATE(28), 1,
      aux_sym_selector_arguments_repeat1,
  [410] = 3,
    ACTIONS(101), 1,
      anon_sym_COMMA,
    ACTIONS(120), 1,
      anon_sym_RBRACK,
    STATE(30), 1,
      aux_sym_selector_arguments_repeat1,
  [420] = 3,
    ACTIONS(101), 1,
      anon_sym_COMMA,
    ACTIONS(122), 1,
      anon_sym_RBRACK,
    STATE(28), 1,
      aux_sym_selector_arguments_repeat1,
  [430] = 2,
    ACTIONS(124), 1,
      aux_sym_rest_token1,
    STATE(15), 1,
      sym_json,
  [437] = 2,
    ACTIONS(126), 1,
      anon_sym_LBRACK,
    ACTIONS(128), 1,
      sym__ws,
  [444] = 2,
    ACTIONS(130), 1,
      aux_sym_rest_token1,
    STATE(13), 1,
      sym_rest,
  [451] = 2,
    ACTIONS(130), 1,
      aux_sym_rest_token1,
    STATE(10), 1,
      sym_rest,
  [458] = 1,
    ACTIONS(132), 2,
      sym_integer,
      sym_text,
  [463] = 1,
    ACTIONS(118), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [468] = 1,
    ACTIONS(134), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [473] = 1,
    ACTIONS(136), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [478] = 1,
    ACTIONS(128), 2,
      anon_sym_LBRACK,
      sym_replacitem_slot,
  [483] = 1,
    ACTIONS(138), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [488] = 1,
    ACTIONS(140), 1,
      sym__ws,
  [492] = 1,
    ACTIONS(142), 1,
      sym_entity_keyword,
  [496] = 1,
    ACTIONS(144), 1,
      sym__ws,
  [500] = 1,
    ACTIONS(146), 1,
      sym__ws,
  [504] = 1,
    ACTIONS(148), 1,
      sym_replacitem_slot,
  [508] = 1,
    ACTIONS(150), 1,
      sym_run_keyword,
  [512] = 1,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
  [516] = 1,
    ACTIONS(154), 1,
      sym__ws,
  [520] = 1,
    ACTIONS(156), 1,
      sym_integer,
  [524] = 1,
    ACTIONS(158), 1,
      sym_run_keyword,
  [528] = 1,
    ACTIONS(160), 1,
      anon_sym_EQ,
  [532] = 1,
    ACTIONS(162), 1,
      sym_run_keyword,
  [536] = 1,
    ACTIONS(164), 1,
      anon_sym_EQ,
  [540] = 1,
    ACTIONS(111), 1,
      sym_replacitem_slot,
  [544] = 1,
    ACTIONS(111), 1,
      sym__ws,
  [548] = 1,
    ACTIONS(166), 1,
      sym__ws,
  [552] = 1,
    ACTIONS(146), 1,
      sym_replacitem_slot,
  [556] = 1,
    ACTIONS(144), 1,
      sym_replacitem_slot,
  [560] = 1,
    ACTIONS(154), 1,
      sym_replacitem_slot,
  [564] = 1,
    ACTIONS(168), 1,
      sym__ws,
  [568] = 1,
    ACTIONS(170), 1,
      sym_item,
  [572] = 1,
    ACTIONS(172), 1,
      sym_run_keyword,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 95,
  [SMALL_STATE(6)] = 121,
  [SMALL_STATE(7)] = 140,
  [SMALL_STATE(8)] = 159,
  [SMALL_STATE(9)] = 178,
  [SMALL_STATE(10)] = 190,
  [SMALL_STATE(11)] = 202,
  [SMALL_STATE(12)] = 214,
  [SMALL_STATE(13)] = 226,
  [SMALL_STATE(14)] = 238,
  [SMALL_STATE(15)] = 250,
  [SMALL_STATE(16)] = 262,
  [SMALL_STATE(17)] = 274,
  [SMALL_STATE(18)] = 286,
  [SMALL_STATE(19)] = 301,
  [SMALL_STATE(20)] = 315,
  [SMALL_STATE(21)] = 329,
  [SMALL_STATE(22)] = 343,
  [SMALL_STATE(23)] = 354,
  [SMALL_STATE(24)] = 364,
  [SMALL_STATE(25)] = 370,
  [SMALL_STATE(26)] = 380,
  [SMALL_STATE(27)] = 390,
  [SMALL_STATE(28)] = 400,
  [SMALL_STATE(29)] = 410,
  [SMALL_STATE(30)] = 420,
  [SMALL_STATE(31)] = 430,
  [SMALL_STATE(32)] = 437,
  [SMALL_STATE(33)] = 444,
  [SMALL_STATE(34)] = 451,
  [SMALL_STATE(35)] = 458,
  [SMALL_STATE(36)] = 463,
  [SMALL_STATE(37)] = 468,
  [SMALL_STATE(38)] = 473,
  [SMALL_STATE(39)] = 478,
  [SMALL_STATE(40)] = 483,
  [SMALL_STATE(41)] = 488,
  [SMALL_STATE(42)] = 492,
  [SMALL_STATE(43)] = 496,
  [SMALL_STATE(44)] = 500,
  [SMALL_STATE(45)] = 504,
  [SMALL_STATE(46)] = 508,
  [SMALL_STATE(47)] = 512,
  [SMALL_STATE(48)] = 516,
  [SMALL_STATE(49)] = 520,
  [SMALL_STATE(50)] = 524,
  [SMALL_STATE(51)] = 528,
  [SMALL_STATE(52)] = 532,
  [SMALL_STATE(53)] = 536,
  [SMALL_STATE(54)] = 540,
  [SMALL_STATE(55)] = 544,
  [SMALL_STATE(56)] = 548,
  [SMALL_STATE(57)] = 552,
  [SMALL_STATE(58)] = 556,
  [SMALL_STATE(59)] = 560,
  [SMALL_STATE(60)] = 564,
  [SMALL_STATE(61)] = 568,
  [SMALL_STATE(62)] = 572,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_say_command, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_say_command, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rest, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rest, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_command, 4, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_execute_command, 4, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tell_command, 4, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tell_command, 4, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tellraw_command, 4, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tellraw_command, 4, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_command, 5, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_execute_command, 5, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replaceitem_command, 6, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replaceitem_command, 6, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_selector_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selector_arguments_repeat1, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_selector_variable, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector_variable, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector_argument, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector_arg_value, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector_arg_value, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector_arguments, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [152] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector_arguments, 4, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_if_subcommand, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector_arg_key, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_in_subcommand, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_unless_subcommand, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mcfunction(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mcfunction",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
